# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'limit_setting.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widget_Limit(object):
    def setupUi(self, widget_Limit):
        widget_Limit.setObjectName("widget_Limit")
        widget_Limit.resize(437, 283)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(widget_Limit)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtWidgets.QLabel(widget_Limit)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_19 = QtWidgets.QLabel(widget_Limit)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.label = QtWidgets.QLabel(widget_Limit)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(widget_Limit)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_7 = QtWidgets.QLabel(widget_Limit)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_17 = QtWidgets.QLabel(widget_Limit)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_3 = QtWidgets.QLabel(widget_Limit)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(widget_Limit)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_18 = QtWidgets.QLabel(widget_Limit)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sb_like = QtWidgets.QSpinBox(widget_Limit)
        self.sb_like.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.sb_like.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sb_like.setMinimum(0)
        self.sb_like.setMaximum(2000)
        self.sb_like.setProperty("value", 999)
        self.sb_like.setDisplayIntegerBase(10)
        self.sb_like.setObjectName("sb_like")
        self.verticalLayout.addWidget(self.sb_like)
        self.sb_unlike = QtWidgets.QSpinBox(widget_Limit)
        self.sb_unlike.setMaximum(2000)
        self.sb_unlike.setProperty("value", 50)
        self.sb_unlike.setObjectName("sb_unlike")
        self.verticalLayout.addWidget(self.sb_unlike)
        self.sb_follow = QtWidgets.QSpinBox(widget_Limit)
        self.sb_follow.setMaximum(2000)
        self.sb_follow.setProperty("value", 999)
        self.sb_follow.setObjectName("sb_follow")
        self.verticalLayout.addWidget(self.sb_follow)
        self.sb_unfollow = QtWidgets.QSpinBox(widget_Limit)
        self.sb_unfollow.setMaximum(2000)
        self.sb_unfollow.setProperty("value", 999)
        self.sb_unfollow.setObjectName("sb_unfollow")
        self.verticalLayout.addWidget(self.sb_unfollow)
        self.sb_comment = QtWidgets.QSpinBox(widget_Limit)
        self.sb_comment.setMaximum(500)
        self.sb_comment.setProperty("value", 149)
        self.sb_comment.setObjectName("sb_comment")
        self.verticalLayout.addWidget(self.sb_comment)
        self.sb_liketolike = QtWidgets.QSpinBox(widget_Limit)
        self.sb_liketolike.setMaximum(10000)
        self.sb_liketolike.setProperty("value", 1500)
        self.sb_liketolike.setObjectName("sb_liketolike")
        self.verticalLayout.addWidget(self.sb_liketolike)
        self.sb_foltofol = QtWidgets.QSpinBox(widget_Limit)
        self.sb_foltofol.setMaximum(100000)
        self.sb_foltofol.setProperty("value", 10000)
        self.sb_foltofol.setObjectName("sb_foltofol")
        self.verticalLayout.addWidget(self.sb_foltofol)
        self.sb_min_foltofol = QtWidgets.QSpinBox(widget_Limit)
        self.sb_min_foltofol.setMaximum(1000)
        self.sb_min_foltofol.setProperty("value", 10)
        self.sb_min_foltofol.setObjectName("sb_min_foltofol")
        self.verticalLayout.addWidget(self.sb_min_foltofol)
        self.sb_fingtofol = QtWidgets.QSpinBox(widget_Limit)
        self.sb_fingtofol.setMaximum(8000)
        self.sb_fingtofol.setProperty("value", 7500)
        self.sb_fingtofol.setObjectName("sb_fingtofol")
        self.verticalLayout.addWidget(self.sb_fingtofol)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_14 = QtWidgets.QLabel(widget_Limit)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_6 = QtWidgets.QLabel(widget_Limit)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(widget_Limit)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(widget_Limit)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_8 = QtWidgets.QLabel(widget_Limit)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.label_15 = QtWidgets.QLabel(widget_Limit)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_13 = QtWidgets.QLabel(widget_Limit)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.label_10 = QtWidgets.QLabel(widget_Limit)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(widget_Limit)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sb_min_fingtofol = QtWidgets.QSpinBox(widget_Limit)
        self.sb_min_fingtofol.setMaximum(8000)
        self.sb_min_fingtofol.setProperty("value", 10)
        self.sb_min_fingtofol.setObjectName("sb_min_fingtofol")
        self.verticalLayout_3.addWidget(self.sb_min_fingtofol)
        self.sb_fertofing = QtWidgets.QSpinBox(widget_Limit)
        self.sb_fertofing.setMaximum(10000)
        self.sb_fertofing.setProperty("value", 1000)
        self.sb_fertofing.setObjectName("sb_fertofing")
        self.verticalLayout_3.addWidget(self.sb_fertofing)
        self.sb_fingtofer = QtWidgets.QSpinBox(widget_Limit)
        self.sb_fingtofer.setProperty("value", 1)
        self.sb_fingtofer.setObjectName("sb_fingtofer")
        self.verticalLayout_3.addWidget(self.sb_fingtofer)
        self.sb_min_media = QtWidgets.QSpinBox(widget_Limit)
        self.sb_min_media.setMaximum(1000)
        self.sb_min_media.setProperty("value", 2)
        self.sb_min_media.setObjectName("sb_min_media")
        self.verticalLayout_3.addWidget(self.sb_min_media)
        self.sb_like_delay = QtWidgets.QSpinBox(widget_Limit)
        self.sb_like_delay.setMaximum(1000)
        self.sb_like_delay.setProperty("value", 40)
        self.sb_like_delay.setObjectName("sb_like_delay")
        self.verticalLayout_3.addWidget(self.sb_like_delay)
        self.sb_unlike_delay = QtWidgets.QSpinBox(widget_Limit)
        self.sb_unlike_delay.setMaximum(1000)
        self.sb_unlike_delay.setProperty("value", 40)
        self.sb_unlike_delay.setObjectName("sb_unlike_delay")
        self.verticalLayout_3.addWidget(self.sb_unlike_delay)
        self.sb_follow_delay = QtWidgets.QSpinBox(widget_Limit)
        self.sb_follow_delay.setMaximum(1000)
        self.sb_follow_delay.setProperty("value", 40)
        self.sb_follow_delay.setObjectName("sb_follow_delay")
        self.verticalLayout_3.addWidget(self.sb_follow_delay)
        self.sb_unfollow_delay = QtWidgets.QSpinBox(widget_Limit)
        self.sb_unfollow_delay.setMaximum(1000)
        self.sb_unfollow_delay.setProperty("value", 30)
        self.sb_unfollow_delay.setObjectName("sb_unfollow_delay")
        self.verticalLayout_3.addWidget(self.sb_unfollow_delay)
        self.sb_comment_delay = QtWidgets.QSpinBox(widget_Limit)
        self.sb_comment_delay.setMaximum(1000)
        self.sb_comment_delay.setProperty("value", 400)
        self.sb_comment_delay.setObjectName("sb_comment_delay")
        self.verticalLayout_3.addWidget(self.sb_comment_delay)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(widget_Limit)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.le_proxy = QtWidgets.QLineEdit(widget_Limit)
        self.le_proxy.setStatusTip("")
        self.le_proxy.setWhatsThis("")
        self.le_proxy.setAccessibleName("")
        self.le_proxy.setAccessibleDescription("")
        self.le_proxy.setInputMask("")
        self.le_proxy.setText("")
        self.le_proxy.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.le_proxy.setClearButtonEnabled(False)
        self.le_proxy.setObjectName("le_proxy")
        self.horizontalLayout_4.addWidget(self.le_proxy)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pb_save = QtWidgets.QPushButton(widget_Limit)
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout_4.addWidget(self.pb_save)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.label_16.setBuddy(self.sb_like)
        self.label_19.setBuddy(self.sb_unlike)
        self.label.setBuddy(self.sb_follow)
        self.label_2.setBuddy(self.sb_unfollow)
        self.label_7.setBuddy(self.sb_comment)
        self.label_17.setBuddy(self.sb_liketolike)
        self.label_3.setBuddy(self.sb_foltofol)
        self.label_5.setBuddy(self.sb_min_foltofol)
        self.label_18.setBuddy(self.sb_fingtofol)
        self.label_14.setBuddy(self.sb_min_fingtofol)
        self.label_6.setBuddy(self.sb_fertofing)
        self.label_9.setBuddy(self.sb_fingtofer)
        self.label_12.setBuddy(self.sb_min_media)
        self.label_8.setBuddy(self.sb_like_delay)
        self.label_15.setBuddy(self.sb_unlike_delay)
        self.label_13.setBuddy(self.sb_follow_delay)
        self.label_10.setBuddy(self.sb_unfollow_delay)
        self.label_11.setBuddy(self.sb_comment_delay)

        self.retranslateUi(widget_Limit)
        QtCore.QMetaObject.connectSlotsByName(widget_Limit)

    def retranslateUi(self, widget_Limit):
        _translate = QtCore.QCoreApplication.translate
        widget_Limit.setWindowTitle(_translate("widget_Limit", "Limit"))
        self.label_16.setText(_translate("widget_Limit", "Max likes per day:"))
        self.label_19.setText(_translate("widget_Limit", "Max unlikes per day:"))
        self.label.setText(_translate("widget_Limit", "Max follows per day:"))
        self.label_2.setText(_translate("widget_Limit", "Max unfollows per day:"))
        self.label_7.setText(_translate("widget_Limit", "Max comments per day:"))
        self.label_17.setText(_translate("widget_Limit", "Max likes to like:"))
        self.label_3.setText(_translate("widget_Limit", "Max followers to follow:"))
        self.label_5.setText(_translate("widget_Limit", "Min followers to follow:"))
        self.label_18.setText(_translate("widget_Limit", "Max following to follow:"))
        self.label_14.setText(_translate("widget_Limit", "Min following to follow:"))
        self.label_6.setText(_translate("widget_Limit", "Max followers to following_ratio:"))
        self.label_9.setText(_translate("widget_Limit", "Max following to followers_ratio:"))
        self.label_12.setText(_translate("widget_Limit", "Min media_count to follow:"))
        self.label_8.setText(_translate("widget_Limit", "Like delay:"))
        self.label_15.setText(_translate("widget_Limit", "Unlike delay:"))
        self.label_13.setText(_translate("widget_Limit", "Follow delay:"))
        self.label_10.setText(_translate("widget_Limit", "Unfollow delay:"))
        self.label_11.setText(_translate("widget_Limit", "Comment delay:"))
        self.label_4.setText(_translate("widget_Limit", "Proxy:"))
        self.le_proxy.setPlaceholderText(_translate("widget_Limit", "Ip Adress"))
        self.pb_save.setText(_translate("widget_Limit", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_Limit = QtWidgets.QWidget()
    ui = Ui_widget_Limit()
    ui.setupUi(widget_Limit)
    widget_Limit.show()
    sys.exit(app.exec_())

