# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 377)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/Bokehlicia-Captiva-Rocket.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_Account = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pb_Account.setFont(font)
        self.pb_Account.setAutoFillBackground(False)
        self.pb_Account.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icon/Graphicloads-Flat-Finance-Lock.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Account.setIcon(icon1)
        self.pb_Account.setIconSize(QtCore.QSize(25, 25))
        self.pb_Account.setAutoDefault(False)
        self.pb_Account.setDefault(False)
        self.pb_Account.setFlat(False)
        self.pb_Account.setObjectName("pb_Account")
        self.verticalLayout.addWidget(self.pb_Account)
        self.pb_whitelist = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_whitelist.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icon/Papirus-Team-Papirus-Places-Folder-green-activities.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_whitelist.setIcon(icon2)
        self.pb_whitelist.setIconSize(QtCore.QSize(25, 25))
        self.pb_whitelist.setObjectName("pb_whitelist")
        self.verticalLayout.addWidget(self.pb_whitelist)
        self.pb_Follow = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_Follow.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icon/Graphicloads-100-Flat-2-People.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Follow.setIcon(icon3)
        self.pb_Follow.setIconSize(QtCore.QSize(25, 25))
        self.pb_Follow.setAutoDefault(False)
        self.pb_Follow.setObjectName("pb_Follow")
        self.verticalLayout.addWidget(self.pb_Follow)
        self.pb_Dm = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_Dm.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icon/Graphicloads-100-Flat-2-Email.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Dm.setIcon(icon4)
        self.pb_Dm.setIconSize(QtCore.QSize(25, 25))
        self.pb_Dm.setAutoDefault(False)
        self.pb_Dm.setObjectName("pb_Dm")
        self.verticalLayout.addWidget(self.pb_Dm)
        self.pb_Like = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_Like.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icon/Double-J-Design-Origami-Colored-Pencil-Red-heart.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Like.setIcon(icon5)
        self.pb_Like.setIconSize(QtCore.QSize(25, 25))
        self.pb_Like.setAutoDefault(False)
        self.pb_Like.setObjectName("pb_Like")
        self.verticalLayout.addWidget(self.pb_Like)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pb_Limit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_Limit.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icon/Bokehlicia-Captiva-Preferences.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Limit.setIcon(icon6)
        self.pb_Limit.setIconSize(QtCore.QSize(25, 25))
        self.pb_Limit.setAutoDefault(False)
        self.pb_Limit.setObjectName("pb_Limit")
        self.verticalLayout_2.addWidget(self.pb_Limit)
        self.pb_blacklist = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_blacklist.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icon/Papirus-Team-Papirus-Places-Folder-red-activities.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_blacklist.setIcon(icon7)
        self.pb_blacklist.setIconSize(QtCore.QSize(25, 25))
        self.pb_blacklist.setObjectName("pb_blacklist")
        self.verticalLayout_2.addWidget(self.pb_blacklist)
        self.pb_Unfollow = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_Unfollow.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Icon/Oxygen-Icons.org-Oxygen-Actions-list-remove-user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Unfollow.setIcon(icon8)
        self.pb_Unfollow.setIconSize(QtCore.QSize(25, 25))
        self.pb_Unfollow.setAutoDefault(False)
        self.pb_Unfollow.setObjectName("pb_Unfollow")
        self.verticalLayout_2.addWidget(self.pb_Unfollow)
        self.pb_Comment = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_Comment.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Icon/Graphicloads-100-Flat-2-Chat-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Comment.setIcon(icon9)
        self.pb_Comment.setIconSize(QtCore.QSize(25, 25))
        self.pb_Comment.setAutoDefault(False)
        self.pb_Comment.setObjectName("pb_Comment")
        self.verticalLayout_2.addWidget(self.pb_Comment)
        self.pb_Reset = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_Reset.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Icon/Bokehlicia-Captiva-Deja-dup.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Reset.setIcon(icon10)
        self.pb_Reset.setIconSize(QtCore.QSize(25, 25))
        self.pb_Reset.setAutoDefault(False)
        self.pb_Reset.setObjectName("pb_Reset")
        self.verticalLayout_2.addWidget(self.pb_Reset)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setStyleSheet("")
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setTristate(False)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_2.addWidget(self.checkBox_5)
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setWhatsThis("")
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_2.addWidget(self.checkBox_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_6.addWidget(self.textEdit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pb_Stop = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_Stop.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Icon/Graphicloads-100-Flat-Stop-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Stop.setIcon(icon11)
        self.pb_Stop.setIconSize(QtCore.QSize(25, 25))
        self.pb_Stop.setObjectName("pb_Stop")
        self.horizontalLayout_4.addWidget(self.pb_Stop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pb_Start = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_Start.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Icon/Graphicloads-100-Flat-Play.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Start.setIcon(icon12)
        self.pb_Start.setIconSize(QtCore.QSize(25, 25))
        self.pb_Start.setAutoDefault(False)
        self.pb_Start.setObjectName("pb_Start")
        self.horizontalLayout_4.addWidget(self.pb_Start)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionRenew_License = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../../.designer/backup/Icon/Graphicloads-100-Flat-2-Arrow-refresh-4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRenew_License.setIcon(icon13)
        self.actionRenew_License.setObjectName("actionRenew_License")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../../.designer/backup/Icon/Hopstarter-Sleek-Xp-Basic-Close.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionClose.setIcon(icon14)
        self.actionClose.setObjectName("actionClose")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../../../.designer/backup/Icon/Icons8-Windows-8-User-Interface-Logout.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionLogout.setIcon(icon15)
        self.actionLogout.setObjectName("actionLogout")
        self.actionTerms = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../../../.designer/backup/Icon/Hopstarter-Sleek-Xp-Basic-Document-Write.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionTerms.setIcon(icon16)
        self.actionTerms.setObjectName("actionTerms")
        self.actionAbout_Virtual_Mode = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../../../.designer/backup/Icon/Oxygen-Icons.org-Oxygen-Actions-help-about.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbout_Virtual_Mode.setIcon(icon17)
        self.actionAbout_Virtual_Mode.setObjectName("actionAbout_Virtual_Mode")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionLast_Activities = QtWidgets.QAction(MainWindow)
        self.actionLast_Activities.setObjectName("actionLast_Activities")
        self.actionClear_Log = QtWidgets.QAction(MainWindow)
        self.actionClear_Log.setObjectName("actionClear_Log")
        self.menuFile.addAction(self.actionLast_Activities)
        self.menuFile.addAction(self.actionClear_Log)
        self.menuFile.addAction(self.actionUpdate)
        self.menuFile.addAction(self.actionRenew_License)
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionTerms)
        self.menuHelp.addAction(self.actionAbout_Virtual_Mode)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionClear_Log.triggered.connect(self.textEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_Account.setText(_translate("MainWindow", "ACCOUNT"))
        self.pb_whitelist.setText(_translate("MainWindow", "WHITELIST"))
        self.pb_Follow.setText(_translate("MainWindow", "FOLLOW"))
        self.pb_Dm.setText(_translate("MainWindow", "DM"))
        self.pb_Like.setText(_translate("MainWindow", "LIKE"))
        self.pb_Limit.setText(_translate("MainWindow", "LIMIT"))
        self.pb_blacklist.setText(_translate("MainWindow", "BLACKLIST"))
        self.pb_Unfollow.setText(_translate("MainWindow", "UNFOLLOW"))
        self.pb_Comment.setText(_translate("MainWindow", "COMMENT"))
        self.pb_Reset.setText(_translate("MainWindow", "RESET"))
        self.label.setText(_translate("MainWindow", "Running:"))
        self.checkBox.setText(_translate("MainWindow", "Follow"))
        self.checkBox_2.setText(_translate("MainWindow", "Unfollow"))
        self.checkBox_3.setText(_translate("MainWindow", "Comment"))
        self.checkBox_5.setText(_translate("MainWindow", "Like"))
        self.checkBox_4.setText(_translate("MainWindow", "Direct Message"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ff007f;\">Welcome to Virtual Mode</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enjoy Your Fully Secured Automation Software</p></body></html>"))
        self.pb_Stop.setText(_translate("MainWindow", "STOP"))
        self.pb_Start.setText(_translate("MainWindow", "START"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionRenew_License.setText(_translate("MainWindow", "Renew License"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionTerms.setText(_translate("MainWindow", "Terms"))
        self.actionAbout_Virtual_Mode.setText(_translate("MainWindow", "About Virtual Mode"))
        self.actionUpdate.setText(_translate("MainWindow", "Update"))
        self.actionLast_Activities.setText(_translate("MainWindow", "Last Activities log"))
        self.actionClear_Log.setText(_translate("MainWindow", "Clear Log"))

    def show_message(self):
        QtWidgets.QMessageBox.warning(self, "Ooopps", "Get this beta version")
        #print("hello world")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

